### ISSUE TITLE
Cut New Release to Make Batch Scraping Configurable via Scraper Chart 

### ISSUE THREAD

**Issue by hkfgo** [promitor/charts#174]
Currently users won't be able to configure batch scraping if they deploy Promitor with these charts.

**Comment by hkfgo** [comment]
The chart change is already merged here: https://github.com/promitor/charts/commit/cbe1b103dacaa37feeda6b6e49cab9848436906d. We should be in good shape to release

**Comment by tomkerkhove** [comment]
Those are not really the changes I meant but let me do it!

**Comment by tomkerkhove** [comment]
https://github.com/promitor/charts/releases/tag/Scraper-v2.13.0 & https://github.com/promitor/charts/releases/tag/ResourceDiscovery-v0.12.0 are out!
