### ISSUE TITLE
Default promitor scraper values generates invalid metrics-declaration.yaml configuration

### ISSUE THREAD

**Issue by danielpof** [promitor/charts#64]
When leaving the metrics value at it's default `metrics: []` it generates an invalid `metrics-declarions.yaml` configuration due to creating a line break bettween `metrics:` and `[]`

## Expected Behavior

Default metrics value should deploy a promitor instance with a valid configuration.

valid config:
```yaml
metrics: []
```

## Actual Behavior

Promitor fails to launch due to invalid `metrics-declarions.yaml` configuration.

invalid config:
```yaml
metrics:
  []
```

## Steps to Reproduce the Problem

  1. Deploy promitor scraper with default values for metrics

## Specifications

  - Version: 2.6.0
  - Platform:
  - Subsystem:

**Comment by tomkerkhove** [comment]
Thank you for reporting, are you willing to open a PR?

**Comment by daniel-anova** [comment]
> Thank you for reporting, are you willing to open a PR?

Honestly never edited a helm chart, but here's my attempt https://github.com/promitor/charts/pull/65
