### ISSUE TITLE
Provide secure-by-default for Promitor Resource Discovery agent

### ISSUE THREAD

**Issue by tomkerkhove** [promitor/charts#71]
Provide secure-by-default for Promitor Resource Discovery agent similar to https://github.com/promitor/charts/pull/70

**Comment by githubcdr** [comment]
Don't forget to add emptyDir to the psp

**Comment by emillunde** [comment]
I can apply the same changes as in #70 and test if the resource discovery agent is working as expected. If it does, are you open to receiving a PR @tomkerkhove?
